### ISSUE TITLE
Link do instagram quebrado

### ISSUE THREAD

**Issue by LeoDKVT** [interaminense/interaminense.github.io#14]
Olá Irmão, ficou top a página, percebi que o link do instagram consta quebrado quando clicar.

**Comment by interaminense** [comment]
Fala Leo, muito obrigado pelo feedback, consegue me ajudar a testar novamente? Eu nao fiz nenhuma modificacao, pra mim ta funcionando, qual foi o browser que vc usou? Foi algum smartphone?

**Comment by LeoDKVT** [comment]
Fiz alguns testes aqui e notei que quando a pessoa não está logado pelo computador aparece essa seguinte mensagem:

![image](https://user-images.githubusercontent.com/84552433/232341902-0c8f6c2a-705c-4a01-8cb6-2405f5db728c.png)

Após fazer o login na minha conta abriu normalmente o seu perfil. 
Então está tudo certo com seu código, culpa do instagram rsrs

**Comment by interaminense** [comment]
Ah, verdade, aconteceu comigo tbm depois que eu me desloguei do instagram pelo browser, valeu Leo!
